
# Configures the HTTP service provided by this service
httpService:
  # Where to bind the HTTP server
  address: 0.0.0.0
  port: 9181
  defaultProxyRule: scyllaDB


# A map of configured proxy rules
proxyRules:
  # For ScyllaDB
  scyllaDB:
    remove:
    - and:
      # let's drop all scylla_column_family_*
      - regexp: ^scylla_column_family_.*

      # but keep scylla_column_family_live_disk_space
      - regexp: ^scylla_column_family_live_disk_space.*
        negate: true
      # and scylla_column_family_live_sstable
      - regexp: ^scylla_column_family_live_sstable.*
        negate: true
      # and scylla_column_family_total_disk_space
      - regexp: ^scylla_column_family_total_disk_space.*
        negate: true

    # note: 'include' takes precedence over 'remove' - can vote back a line!
    include:
